version: '3.5'

services:

  app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: ceisc-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      ceisc:
        aliases:
          - ceisc-app

  mysql:
    image: mysql:5.7
    container_name: ceisc-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-password
      - MYSQL_DATABASE=challenge
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=super-secret-password
    networks:
      ceisc:
        aliases:
          - ceisc-db

networks:
  ceisc:
    name: ceisc-network
